### ISSUE TITLE
Setup reconftw after axiom 

### ISSUE THREAD

**Issue by spazbg** [six2dez/reconftw#253]
Hello, awesome devs. 
I have an old instance of axiom already set up. If I want to add reconftw am I supposed to drop the old instance and create a new VPS, install reconftw first, and then set up the axiom or I can just install reconftw on my axiom instance.

**Comment by six2dez** [comment]
Hi! For using reconftw_axiom is required to run ./install.sh in your pc (axiom's controller/main host/whatever you call it) because some tasks is performed by main host. About the axiom's instances (a.k.a. the fleet) the best way is to run axiom-configure and select the provider "reconftw", which already have all the tools installed and then set up a new fleet with the new image created.

**Comment by spazbg** [comment]
Thank you very much for the answer and again for the awesome tool. 
What's the difference between these two approaches, and which is recommended for VPS(DO) usage?
I have installed reconftw on my VPS, where I have axiom installed already, through the install.sh script and ran a single thread/instance scan with reconftw.sh which take 1:30h and now I want to distribute the scan between fleets with axiom and check the new recon time. 
Whats are the next steps, creating few fleets and calling the axiom-configure?

**Comment by six2dez** [comment]
Nope, you need first to build a new reconftw packer image with axiom-configure, then set up the fleet with that image. At this point you will have a fleet prepared to run reconftw_axiom.sh :) hope this will answer your question

**Comment by spazbg** [comment]
I think I got it now. Thanks for the help!
