### ISSUE TITLE
[Question] line 318 on reconftw.sh

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#294]
Hi,
What happens to passive_subs.txt after? Is it not run through anything after this or am I missing something.
after (line 318) NUMOFLINES=$(cat .tmp/*_psub.txt 2>>"$LOGFILE" | sed "s/*.//" | anew .tmp/passive_subs.txt | wc -l)
I can't find a reference to passive_subs.txt
Should it not put the contents of .tmp/passive_subs.txt in to webs.txt to scan all these subs? (ran through httpx first) 
It seems it's missing alot of subs compaired to my usual slow way of gathering subs. (tried full also)
Again... I could be missing something.
Thanks

**Comment by detonxx** [comment]
* The passive subs file and crt.sh file are combined and  then sent to DNS resolution.
* Check out line number 348 https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L348.
* Here we have used a regular expression "*" to get all the contains of file ending with `_subs.txt` into one single file and then send it for resolution.  

Thus you didn't get the required file "passive_subs.txt" upon searching as we use a regular expression (*_subs.txt) so that the file comes into consideration.

**Comment by gprime31** [comment]
Ah okay, thanks for the quick reply :) Great work you guys are doing btw.
