### ISSUE TITLE
Merge install and update scripts

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#52]
Merge install and update scripts in one, let's say "tools.sh". It will install the tools if not installed or update if exist.

**Comment by hackingguy** [comment]
To make installation faster we can provide go binaries precompiled rather than doing go get to build the binary as most of the users are using it on x86 architecture! we can check architecture and on the basis of that if it is not x86 we can perform a build else we can go with just moving our precompiled folder to the go/bin directory!

**Comment by bileltechno** [comment]
@hackingguy  : Most of those tools don't provide pre-compiled binaries in their github release page.
And no one should trust a third party compiled binaries. So we need to compile those not compiled and download those already compiled by the owner.
Thanks for your feedbak.
Issue already created :[#55]( https://github.com/six2dez/reconftw/issues/55)

**Comment by six2dez** [comment]
Done https://github.com/six2dez/reconftw/commit/e25426165a94cc40722f0e61d25ab2575de323f3
