### ISSUE TITLE
cdnprovider was not working

### ISSUE THREAD

**Issue by ptgeft** [six2dez/reconftw#573]
Hi! When I did a code review, I found that `cdnprovider()` will not work because it needs the `$dir/hosts/ips.txt` file to exist:

https://github.com/six2dez/reconftw/blob/ea5ad46fb593caa92e82a7a5341a9be7b07bbb1a/reconftw.sh#L993-L997

and `ips.txt` appears to be generated by the `portscan()` function which runs after cdnprovider, so `cdnprovider()` will not work

https://github.com/six2dez/reconftw/blob/ea5ad46fb593caa92e82a7a5341a9be7b07bbb1a/reconftw.sh#L952-L959

https://github.com/six2dez/reconftw/blob/ea5ad46fb593caa92e82a7a5341a9be7b07bbb1a/reconftw.sh#L2259-L2262

in conclude: should we change the order?

```diff
	virtualhosts
--	cdnprovider
	portscan
++	cdnprovider
	waf_checks
```

**Comment by six2dez** [comment]
Hey!!! Well spotted! The issue is what you said, but the solution will not be exactly that, because the main point of cdnprovider (or the `ipcdn` tool) is to detect the IPs under CDN to avoid port scans on them, but also inform to the user the CDN providers usage.

If you look at the code here: https://github.com/six2dez/reconftw/blob/ea5ad46fb593caa92e82a7a5341a9be7b07bbb1a/reconftw.sh#L961 the tool is used for one of the purposes, but as you said the other purpose (inform the user about the CDNs in use) is not working well, so for this I will apply this fix: https://github.com/six2dez/reconftw/commit/181cc2e4c05fcd402ef53fbbb9e87e3f9ff88d7c where it extracts the IP list from DNS records in the same way as portscans. 

Of course, your solution would work too, but I found myself looking at the CDN providers while the port scan is running just to check which ones have been skipped.
