### ISSUE TITLE
cannot run reconftw in macbookpro m1 chip

### ISSUE THREAD

**Issue by AzhariRamadhan** [six2dez/reconftw#596]
**Describe the bug**
cannot check update and running command
<img width="762" alt="Jepretan Layar 2022-10-04 pukul 20 02 23" src="https://user-images.githubusercontent.com/32870854/193826117-a80aa222-5326-40c3-a873-738db6999b50.png">

**To Reproduce**
run ./reconftw.sh -d target.com -r

**Expected behavior**
cannot show result

**Screenshots**
<img width="762" alt="Jepretan Layar 2022-10-04 pukul 19 55 25" src="https://user-images.githubusercontent.com/32870854/193825031-60d6b177-b0fe-48f5-9e10-436207b785fe.png">

**Desktop (please complete the following information):**
- Architecture: [x64, ARM ...]
 - OS: [m1 chip ...]
 - Version [12.6]

**Comment by Vorshik** [comment]
Hi! Had the same bug.
Here I can propose you a solution because I really don't know how to fix it in code itself.
The application uses `getopt` to parse options (Refer to the [link](https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L2735)).
The problem is that there are two different versions of `getopt`, basic `getopt` and `GNU getopt`. Basic `getopt` has tons of issues with the handling of long options and options with spaces (For more details refer to [stackoverflow](https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options)). 
As you may guess OS X has exactly the Basic `getopt` installed. 

My solution is to install GNU `getopt`. For these purpose use the following commands:

`brew install gnu-getopt`

Next you should place `gnu-getopt` first in your `PATH`:

`echo 'export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc`

Maybe it's not a good solutions but at the same time it works without changes into a source code. 

Best Regards.

**Comment by six2dez** [comment]
> Hi! Had the same bug. Here I can propose you a solution because I really don't know how to fix it in code itself. The application uses `getopt` to parse options (Refer to the [link](https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L2735)). The problem is that there are two different versions of `getopt`, basic `getopt` and `GNU getopt`. Basic `getopt` has tons of issues with the handling of long options and options with spaces (For more details refer to [stackoverflow](https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options)). As you may guess OS X has exactly the Basic `getopt` installed.
> 
> My solution is to install GNU `getopt`. For these purpose use the following commands:
> 
> `brew install gnu-getopt`
> 
> Next you should place `gnu-getopt` first in your `PATH`:
> 
> `echo 'export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc`
> 
> Maybe it's not a good solutions but at the same time it works without changes into a source code.
> 
> Best Regards.

I've updated the installer on dev branch, can you @Vorshik test again with dev version? You have to change to dev branch, run the installer and the run reconftw. Thanks!

**Comment by AzhariRamadhan** [comment]
<img width="762" alt="Jepretan Layar 2022-10-14 pukul 19 16 06" src="https://user-images.githubusercontent.com/32870854/195844677-e7b28839-3c98-412a-ade1-3145de8ee890.png">

not fixed yet

**Comment by six2dez** [comment]
Have you tried to run it in a new fresh spawned terminal? As it may reload the PATH env

**Comment by AzhariRamadhan** [comment]
fix. thanks

**Comment by Vorshik** [comment]
Hi @six2dez ! Sorry for the late response. The fix works great. Didn't thought about changing the installation file as I just debugged the reconftw.sh file 😄 
But as you use brew inside its a perfect solution. 

Best Regards.
