### ISSUE TITLE
Docker file Update

### ISSUE THREAD

**Issue by parvbarot** [six2dez/reconftw#674]
Can u update the docker file with the latest update?

**Comment by 0-0eth0** [comment]
Hi,
is there any error you are facing?

**Comment by JaredStemper** [comment]
I'm not sure if parvbarot ran into the same issue as myself, but having just tested the dockerized approach, I can confirm that it does not work out of the box on my side (used a fresh docker image - which denotes the version as main-v2.5.2-20-gc8dfd2e).

Running subdomain enumeration on a standard bug bounty website using the default command given on the Wiki for docker:
![image](https://user-images.githubusercontent.com/31346981/227751039-2c7fe319-d6ac-4292-b984-3a537871cf03.png)

![image](https://user-images.githubusercontent.com/31346981/227751072-4580b821-4cb4-4ee0-a834-5151da72845d.png)

![image](https://user-images.githubusercontent.com/31346981/227751081-af7c97ce-1550-4f9f-81c7-c02cbcede154.png)

![image](https://user-images.githubusercontent.com/31346981/227751087-35b87615-78d7-4114-bc24-243bb24bde5d.png)


The final output directory was created but no files were placed in it.
![image](https://user-images.githubusercontent.com/31346981/227751175-854bb869-bce3-478b-a919-c477890d041a.png)


When running with the standard `-r` argument, I believe the issue is slightly more clear.
![image](https://user-images.githubusercontent.com/31346981/227751129-ef8c2b03-d6d9-4a1b-b3dc-5e5e73b72e1c.png)

I like the shape this project has taken and am interested in helping support efforts in the future, but I am very new to this tool and don't have the capacity at this time to troubleshoot in great depth.

**Comment by six2dez** [comment]
The Dockerfile image on DockerHub and the Dockerfile itself has been updated recently, these changes should fix this issue.
