### ISSUE TITLE
cannot touch file

### ISSUE THREAD

**Issue by Hoodie2389** [six2dez/reconftw#713]
Hi 

Aside from the tools that isnt installed automatically by the install.sh - I got this error msg when trying to run it - and looks like this function finishes quite quickly with no result - the other modules are the same - can you point out what went wrong? Thanks

 Searching domain info (whois, registrant name/email domains) 
touch: cannot touch 'tools/reconftw/Recon/cacti.htb/.called_fn/.domain_info': No such file or directory

 domain_info Finished in 1 seconds. 
 Results are saved in cacti.htb/osint/domain_info_[general/name/email/ip].txt 

Subdomain Enumeration cacti.htb

 Running : Passive Subdomain Enumeration 
touch: cannot touch 'tools/reconftw/Recon/cacti.htb/.called_fn/.sub_passive': No such file or directory

 0 new subs (passive) in 36 seconds. 

 Running : Crtsh Subdomain Enumeration 
touch: cannot touch 'tools/reconftw/Recon/cacti.htb/.called_fn/.sub_crt': No such file or directory

 0 new subs (cert transparency) in 7 seconds. 

 Running : Active Subdomain Enumeration 
touch: cannot touch 'tools/reconftw/Recon/cacti.htb/.called_fn/.sub_active': No such file or directory

 0 subs DNS resolved from passive in 2 seconds.

**Comment by DSGuglielmo** [comment]
I'm having the same issue here. I clone the repository and followed the install steps. The installation is successful but I get the same issue. Is it because I'm using MacOS? 

 Running : Active Subdomain Enumeration 
touch: cannot touch '/reconftw/Recon/hackthissite.org/.called_fn/.sub_active': No such file or directory

 1 subs DNS resolved from passive in 3 minutes, 27 seconds. 

 Running : Checking NOERROR DNS response 

 Detected DNSSEC black lies, skipping this technique 

 Running : Bruteforce Subdomain Enumeration

**Comment by DSGuglielmo** [comment]
Thank you for replying so fast. I tried the command with my username but I am unable to proceed because it does not recognise the password. I tried sudo ./install.sh which gave no problems but then when I try ./reconftw.sh -d target.com -r it gives:

 dev-v2.6-82-gdd119a1                                 by @six2dez
error: cannot open .git/FETCH_HEAD: Permission denied
 Unable to check updates

and then 

Required file /Users/DSG/Tools/.github_tokens not exists or empty 
touch: cannot touch '/reconftw/Recon/hackthissite.org/.called_fn/.github_dorks': No such file or directory

for every process step. 

I thought it was an installation problem but I recloned and reinstalled everything also with the dev option.
Any ideas on how to fix it?

Thank you in advance.

**Comment by six2dez** [comment]
Hmmm are you installing it as root? Seems that a permissions problems on your side, but not sure why :/

**Comment by DSGuglielmo** [comment]
Yes, both using sudo and giving myself admin privileges with chown. 
The only problem is: 
touch: cannot touch '/reconftw/Recon/hackthissite.org/.called_fn/.sub_active': No such file or directory

Everything else works.
The folder is completely empty, any ideas?

**Comment by six2dez** [comment]
both the installer and reconftw should **not** be run as sudo, but a normal user
