### ISSUE TITLE
AMASS config.ini empty 

### ISSUE THREAD

**Issue by Darkcast** [six2dez/reconftw#883]
The config.ini is empty, I tried removing config.ini and launching the app and it didnt get created at all :(

 The reason is becasue file was removed which is why is empty 
```
wget -q -O ~/.config/amass/config.ini https://raw.githubusercontent.com/owasp-amass/amass/master/examples/config.ini
```

is there any particular reason why you are installing 3.23 instead of the lastest one 4.20 ?

https://github.com/owasp-amass/amass/releases/tag/v4.2.0

thanks :)

**Comment by Darkcast** [comment]
so it looks like the deprecated confing.ini for config.yaml for the new release. 
https://github.com/owasp-amass/amass/blob/master/examples/config.yaml

**Comment by six2dez** [comment]
At the moment Amass v4 is not able to fetch only passive data because it always resolves the subdomains and only stores and outputs resolved and valid subdomains, that's why I stick to the older version: https://discord.com/channels/433729817918308352/433729817918308354/1220353439163482204

To fix the problem you mentioned, I uploaded the default config.ini for the latest v3 to my gists and the installer will pick it from there (https://gist.github.com/six2dez/b376488a1317242bfa3851e95875cb3b)
at https://github.com/six2dez/reconftw/commit/ea1b7affcfcfd7b39e49121c73c8ced8ff09683f


To be clear, I got it from here: https://github.com/owasp-amass/amass/archive/refs/tags/v3.23.3.zip

**Comment by Darkcast** [comment]
awesome thanks for the help :)
